import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='flex bg-purple-500 gap-5 p-4 px-5 py-5 '>
        <Link href = "/">Home</Link>
        <Link href = "/Todo">Todo</Link>
         </header>
        {children}
        <footer className='flex justify-center bg-slate-400 p-3'>@ Copywrite Reserved 2023 </footer>
        </body>
    </html>
  )
}
